port:  5000
markdown: kramdown
name: "My Reps"
url: http://findmyreps.datamade.us
encoding: utf-8
timezone: America/Detroit
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyBU0e28D2vi588-ymBHBd6Xqk6MlTRduXc
